#!/bin/bash
set -e

PROTO_DIR="./protos"
GO_OUT_DIR="./gen/go"
TS_OUT_DIR="./gen/ts"

mkdir -p "${GO_OUT_DIR}"
mkdir -p "${TS_OUT_DIR}"

while IFS= read -r -d '' PROTO_SUBDIR; do
  PROTO_FILES=$(find "${PROTO_SUBDIR}" -maxdepth 1 -name "*.proto")
  if [ -n "${PROTO_FILES}" ]; then
    SUBDIR_NAME=$(basename "${PROTO_SUBDIR}")

    GO_OUT_SUBDIR="${GO_OUT_DIR}/${SUBDIR_NAME}"
    mkdir -p "${GO_OUT_SUBDIR}"
    protoc \
      -I="${PROTO_SUBDIR}" \
      --go_out="${GO_OUT_SUBDIR}" \
      --go-grpc_out="${GO_OUT_SUBDIR}" \
      --go_opt=paths=source_relative \
      --go-grpc_opt=paths=source_relative \
      ${PROTO_FILES}

    TS_OUT_SUBDIR="${TS_OUT_DIR}/${SUBDIR_NAME}"
    mkdir -p "${TS_OUT_SUBDIR}"
    protoc \
      --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto \
      --ts_proto_out="${TS_OUT_SUBDIR}" \
      --ts_proto_opt=nestJs=true,useObservable=true,outputClientImpl=grpc-js \
      -I "${PROTO_SUBDIR}" \
      ${PROTO_FILES}

    TS_INDEX_FILE="$TS_OUT_SUBDIR/index.ts"
    echo "// Auto-generated by generate.sh" > "$TS_INDEX_FILE"

    TS_OUT_SUBDIR_UPPER=$(echo $(basename "$TS_OUT_SUBDIR") | tr '[:lower:]' '[:upper:]')
    PACKAGE_CONST_PREFIX="${TS_OUT_SUBDIR_UPPER}_PACKAGE_NAME"

    for f in "$TS_OUT_SUBDIR"/*.ts; do
      BASENAME=$(basename "$f" .ts)

      if [[ "$BASENAME" == "index" ]]; then
        continue
      fi

      if [[ "$BASENAME" == service_* ]]; then
        echo "export * from './$BASENAME';" >> "$TS_INDEX_FILE"
      else
        EXCLUDE_PATTERN="${PACKAGE_CONST_PREFIX}|protobufPackage"
        IDENTIFIERS=$(grep -E '^export (interface|type|class|const|function) ' "$f" \
          | awk '{print $3}' \
          | grep -v -E "$EXCLUDE_PATTERN" \
          | paste -sd ',' -)

        if [ -n "$IDENTIFIERS" ]; then
          echo "export { $IDENTIFIERS } from './$BASENAME';" >> "$TS_INDEX_FILE"
        fi
      fi
    done
  fi
done < <(find "${PROTO_DIR}" -type d -print0)